# Generated by Django 5.2.5 on 2025-09-29 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='storage_path',
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
    ]
