# Generated by Django 5.2.5 on 2025-09-29 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_full_name_alter_user_storage_path'),
    ]

    operations = [
    ]
