# Generated by Django 5.2.5 on 2025-10-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_manual_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='storage_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
