# Generated by Django 5.2.5 on 2025-09-03 14:21

import files.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_comment_file_share_token_alter_file_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='is_shared',
        ),
        migrations.AddField(
            model_name='file',
            name='last_downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='original_name',
            field=models.CharField(default='legacy_file', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=files.models.user_storage_path),
        ),
        migrations.AlterField(
            model_name='file',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
